// Bitcoin or Fiat? — Question pool
// Each entry: { text: "...", answer: "bitcoin" | "fiat" }
// 15 Bitcoin properties + 15 Fiat properties per language

const QUESTIONS = {

  en: [
    // ── Bitcoin ──────────────────────────────────────────────────────────────
    { text: "Has a fixed supply cap of exactly 21 million units",                           answer: "bitcoin" },
    { text: "Decentralized — no single authority can ever control it",                      answer: "bitcoin" },
    { text: "Enables peer-to-peer payments without banks or middlemen",                     answer: "bitcoin" },
    { text: "Censorship-resistant — no one can block your transaction",                     answer: "bitcoin" },
    { text: "Allows full self-custody: be your own bank, no counterparty risk",             answer: "bitcoin" },
    { text: "All transactions are permanently and publicly verifiable on-chain",            answer: "bitcoin" },
    { text: "Operates 24/7, 365 days a year, everywhere on Earth",                         answer: "bitcoin" },
    { text: "Supply inflation rate is automatically halved every ~4 years",                 answer: "bitcoin" },
    { text: "No account or ID required — open to every person on the planet",              answer: "bitcoin" },
    { text: "Future supply is mathematically predictable by protocol design",               answer: "bitcoin" },
    { text: "Cannot be devalued by any political or central-bank decision",                 answer: "bitcoin" },
    { text: "Transactions are irreversible and final — no chargebacks",                     answer: "bitcoin" },
    { text: "Permissionless — no institution can deny you access",                          answer: "bitcoin" },
    { text: "Secured by the largest proof-of-work computing network ever built",            answer: "bitcoin" },
    { text: "Not issued by any government, central bank, or corporation",                   answer: "bitcoin" },
    // ── Fiat ─────────────────────────────────────────────────────────────────
    { text: "Can be printed without any fixed supply cap by central banks",                 answer: "fiat" },
    { text: "Loses purchasing power to inflation continuously over time",                   answer: "fiat" },
    { text: "Can be frozen or seized by government authorities",                            answer: "fiat" },
    { text: "Its total supply is decided by governments and central banks",                 answer: "fiat" },
    { text: "Requires trust in banks and financial institutions to function",               answer: "fiat" },
    { text: "Has triggered hyperinflation and currency collapse in many countries",         answer: "fiat" },
    { text: "The US Dollar has lost over 96% of its purchasing power in 100 years",        answer: "fiat" },
    { text: "Banks can refuse, reverse, or delay your transactions",                        answer: "fiat" },
    { text: "Can be devalued overnight by a single central-bank policy decision",           answer: "fiat" },
    { text: "Capital controls can restrict how much money you are allowed to move",         answer: "fiat" },
    { text: "Requires a bank account to fully participate in the modern economy",           answer: "fiat" },
    { text: "Has no fixed maximum supply — more can always be created",                     answer: "fiat" },
    { text: "Its value depends entirely on political and governmental stability",           answer: "fiat" },
    { text: "Can be subject to negative interest rates imposed by central banks",           answer: "fiat" },
    { text: "Has collapsed completely hundreds of times throughout monetary history",        answer: "fiat" },
  ],

  de: [
    // ── Bitcoin ──────────────────────────────────────────────────────────────
    { text: "Hat ein unveränderliches Gesamtangebot von exakt 21 Millionen Einheiten",      answer: "bitcoin" },
    { text: "Dezentral – keine einzelne Instanz kann es jemals kontrollieren",              answer: "bitcoin" },
    { text: "Ermöglicht direkte Peer-to-Peer-Zahlungen ohne Banken oder Mittelsmänner",     answer: "bitcoin" },
    { text: "Zensurresistent – niemand kann eine Transaktion blockieren",                   answer: "bitcoin" },
    { text: "Vollständige Selbstverwahrung möglich – sei deine eigene Bank",               answer: "bitcoin" },
    { text: "Alle Transaktionen sind dauerhaft und öffentlich auf der Blockchain einsehbar",answer: "bitcoin" },
    { text: "Funktioniert rund um die Uhr, 365 Tage im Jahr, weltweit",                    answer: "bitcoin" },
    { text: "Inflationsrate halbiert sich automatisch alle ~4 Jahre (Halving)",             answer: "bitcoin" },
    { text: "Kein Konto und kein Ausweis erforderlich – für jeden Menschen zugänglich",    answer: "bitcoin" },
    { text: "Das zukünftige Angebot ist durch das Protokoll mathematisch vorhersehbar",    answer: "bitcoin" },
    { text: "Kann durch keine politische oder zentralbankseitige Entscheidung entwertet werden", answer: "bitcoin" },
    { text: "Transaktionen sind unwiderruflich und endgültig",                              answer: "bitcoin" },
    { text: "Permissionless – keine Institution kann dir den Zugang verweigern",            answer: "bitcoin" },
    { text: "Gesichert durch das größte Proof-of-Work-Computernetzwerk der Geschichte",    answer: "bitcoin" },
    { text: "Nicht von Regierungen, Zentralbanken oder Unternehmen ausgegeben",            answer: "bitcoin" },
    // ── Fiat ─────────────────────────────────────────────────────────────────
    { text: "Kann von Zentralbanken ohne feste Obergrenze gedruckt werden",                answer: "fiat" },
    { text: "Verliert durch Inflation kontinuierlich an Kaufkraft",                        answer: "fiat" },
    { text: "Kann von Behörden eingefroren oder beschlagnahmt werden",                     answer: "fiat" },
    { text: "Gesamtangebot wird von Regierungen und Zentralbanken festgelegt",             answer: "fiat" },
    { text: "Erfordert Vertrauen in Banken und Finanzinstitutionen",                       answer: "fiat" },
    { text: "Hat in vielen Ländern Hyperinflation und Währungszusammenbrüche ausgelöst",   answer: "fiat" },
    { text: "Der US-Dollar hat in 100 Jahren über 96% seiner Kaufkraft verloren",          answer: "fiat" },
    { text: "Banken können Transaktionen ablehnen, rückgängig machen oder verzögern",      answer: "fiat" },
    { text: "Kann über Nacht durch eine Zentralbankentscheidung abgewertet werden",        answer: "fiat" },
    { text: "Kapitalverkehrskontrollen können erlaubte Geldtransfers einschränken",        answer: "fiat" },
    { text: "Für volle Wirtschaftsteilnahme wird ein Bankkonto benötigt",                  answer: "fiat" },
    { text: "Hat keine feste Angebotsobergrenze – es kann immer mehr geschaffen werden",   answer: "fiat" },
    { text: "Sein Wert hängt vollständig von politischer und staatlicher Stabilität ab",   answer: "fiat" },
    { text: "Kann von Zentralbanken negativen Zinsen unterworfen werden",                  answer: "fiat" },
    { text: "Hat in der Währungsgeschichte bereits hunderte Male komplett versagt",         answer: "fiat" },
  ],

  fr: [
    // ── Bitcoin ──────────────────────────────────────────────────────────────
    { text: "Offre totale fixée à exactement 21 millions d'unités, immuable",              answer: "bitcoin" },
    { text: "Décentralisé — aucune autorité unique ne peut jamais le contrôler",           answer: "bitcoin" },
    { text: "Permet des paiements pair-à-pair directs sans banques ni intermédiaires",     answer: "bitcoin" },
    { text: "Résistant à la censure — personne ne peut bloquer une transaction",           answer: "bitcoin" },
    { text: "Auto-conservation totale possible — soyez votre propre banque",              answer: "bitcoin" },
    { text: "Toutes les transactions sont permanentes et publiquement vérifiables on-chain",answer: "bitcoin" },
    { text: "Fonctionne 24h/24, 7j/7, 365 jours par an, partout dans le monde",          answer: "bitcoin" },
    { text: "Le taux d'inflation est automatiquement divisé par deux tous les ~4 ans",     answer: "bitcoin" },
    { text: "Aucun compte ni pièce d'identité requis — accessible à toute personne",      answer: "bitcoin" },
    { text: "L'offre future est mathématiquement prévisible par le protocole",             answer: "bitcoin" },
    { text: "Ne peut pas être dévalué par une décision politique ou de banque centrale",   answer: "bitcoin" },
    { text: "Les transactions sont irréversibles et définitives — sans rétrofacturation",  answer: "bitcoin" },
    { text: "Sans permission — aucune institution ne peut vous refuser l'accès",          answer: "bitcoin" },
    { text: "Sécurisé par le plus grand réseau proof-of-work jamais construit",           answer: "bitcoin" },
    { text: "Non émis par un gouvernement, une banque centrale ou une entreprise",        answer: "bitcoin" },
    // ── Fiat ─────────────────────────────────────────────────────────────────
    { text: "Peut être imprimé sans plafond d'émission fixe par les banques centrales",   answer: "fiat" },
    { text: "Perd continuellement son pouvoir d'achat à cause de l'inflation",            answer: "fiat" },
    { text: "Peut être gelé ou saisi par les autorités gouvernementales",                  answer: "fiat" },
    { text: "L'offre totale est décidée par les gouvernements et les banques centrales",  answer: "fiat" },
    { text: "Nécessite une confiance accordée aux banques et institutions financières",   answer: "fiat" },
    { text: "A déclenché des hyperinflations et effondrements monétaires dans de nombreux pays", answer: "fiat" },
    { text: "Le dollar américain a perdu plus de 96 % de son pouvoir d'achat en 100 ans", answer: "fiat" },
    { text: "Les banques peuvent refuser, annuler ou retarder vos transactions",          answer: "fiat" },
    { text: "Peut être dévalué du jour au lendemain par une décision de banque centrale", answer: "fiat" },
    { text: "Les contrôles des capitaux peuvent restreindre les transferts autorisés",    answer: "fiat" },
    { text: "Un compte bancaire est requis pour participer pleinement à l'économie",      answer: "fiat" },
    { text: "N'a aucun plafond d'offre fixe — on peut toujours en créer davantage",       answer: "fiat" },
    { text: "Sa valeur dépend entièrement de la stabilité politique et gouvernementale",  answer: "fiat" },
    { text: "Peut être soumis à des taux d'intérêt négatifs imposés par les banques centrales", answer: "fiat" },
    { text: "A échoué complètement des centaines de fois dans l'histoire monétaire",      answer: "fiat" },
  ],

};
